image:
  pullPolicy: IfNotPresent
  repository: romanowalex/echo-server
  tag: v2.0

port: 8080
nodePort: 30010

liveness:
  delay: 15
  timeout: 10
  path: "/manage/health/readiness"
  port: 8080

readiness:
  delay: 15
  timeout: 10
  path: "/manage/health/readiness"
  port: 8080

resources:
  requests:
    cpu: 500m
    memory: 1024Mi
  limits:
    cpu: 500m
    memory: 1024Mi