image:
  pullPolicy: IfNotPresent
  repository: romanowalex/echo-server
  tag: v2.0

ports:
  application: 8080
  jmx: 9000

liveness:
  delay: 15
  timeout: 10
  path: "/manage/health/readiness"
  port: 8080

readiness:
  delay: 15
  timeout: 10
  path: "/manage/health/readiness"
  port: 8080

resources:
  requests:
    cpu: 1
    memory: 1024Mi
  limits:
    cpu: 1
    memory: 1024Mi