image:
  pullPolicy: IfNotPresent
  repository: prom/prometheus
  tag: v2.54.1

port: 9090
nodePort: 30012

resources:
  requests:
    cpu: 500m
    memory: 1024Mi
  limits:
    cpu: 500m
    memory: 1024Mi